/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueryRouteImport } from './routes/query'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueryIndexRouteImport } from './routes/query.index'
import { Route as QueryThreadIdRouteImport } from './routes/query.$threadId'

const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryIndexRoute = QueryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QueryRoute,
} as any)
const QueryThreadIdRoute = QueryThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => QueryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/ingest': typeof IngestRoute
  '/insights': typeof InsightsRoute
  '/query': typeof QueryRouteWithChildren
  '/query/$threadId': typeof QueryThreadIdRoute
  '/query/': typeof QueryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/ingest': typeof IngestRoute
  '/insights': typeof InsightsRoute
  '/query/$threadId': typeof QueryThreadIdRoute
  '/query': typeof QueryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/ingest': typeof IngestRoute
  '/insights': typeof InsightsRoute
  '/query': typeof QueryRouteWithChildren
  '/query/$threadId': typeof QueryThreadIdRoute
  '/query/': typeof QueryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/ingest'
    | '/insights'
    | '/query'
    | '/query/$threadId'
    | '/query/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/graph' | '/ingest' | '/insights' | '/query/$threadId' | '/query'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/ingest'
    | '/insights'
    | '/query'
    | '/query/$threadId'
    | '/query/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  IngestRoute: typeof IngestRoute
  InsightsRoute: typeof InsightsRoute
  QueryRoute: typeof QueryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query/': {
      id: '/query/'
      path: '/'
      fullPath: '/query/'
      preLoaderRoute: typeof QueryIndexRouteImport
      parentRoute: typeof QueryRoute
    }
    '/query/$threadId': {
      id: '/query/$threadId'
      path: '/$threadId'
      fullPath: '/query/$threadId'
      preLoaderRoute: typeof QueryThreadIdRouteImport
      parentRoute: typeof QueryRoute
    }
  }
}

interface QueryRouteChildren {
  QueryThreadIdRoute: typeof QueryThreadIdRoute
  QueryIndexRoute: typeof QueryIndexRoute
}

const QueryRouteChildren: QueryRouteChildren = {
  QueryThreadIdRoute: QueryThreadIdRoute,
  QueryIndexRoute: QueryIndexRoute,
}

const QueryRouteWithChildren = QueryRoute._addFileChildren(QueryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  IngestRoute: IngestRoute,
  InsightsRoute: InsightsRoute,
  QueryRoute: QueryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
